{% set version = "1.0.0" %}

package:
  name: cc-plugin-ugrid
  version: {{ version }}

source:
  url: https://github.com/ioos/cc-plugin-ugrid/archive/v{{ version }}.tar.gz
  sha256: e6fdc0b80eef0a81c3e1bf11c90baa8f3b8fdd498d3fb78e71e22d61196d5d45

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - compliance-checker >=4.0.0
    - netcdf4 >=1.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - cc_plugin_ugrid

about:
  home: https://github.com/ioos/cc-plugin-ugrid
  license: Apache 2.0
  license_file: LICENSE
  summary: UGRID plugin for the IOOS Compliance Checker Plugin

extra:
  recipe-maintainers:
    - ocefpaf
