{% set name = "cc-plugin-ugrid" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cc_plugin_ugrid-{{ version }}.tar.gz
  sha256: 9ba437ab564a25f7f93e4ddc0802c0581faf179832f687eccc744b27f0378c91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - compliance-checker >=4.0.0
    - netcdf4 >=1.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - cc_plugin_ugrid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ioos/cc-plugin-ugrid
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: UGRID plugin for the IOOS Compliance Checker Plugin

extra:
  recipe-maintainers:
    - ocefpaf
