travis:
  secure:
    BINSTAR_TOKEN: oNVvCX/pSwaIplQBGhPeFkKU+/tLB6KsnvOCHRnzVRKXik8aXdroWI6XA9n8Xk6VwyzMue2+OSuZcFOuUbww6oRDcgXzRIWGS5rYYgy/Epb6lcd6NWvf2ZaZVDhoWoCTbTM91YY2gnMTB3fpw6Z9CasPiE3TJBCbxekyaAX7kb356KI3LVNSqZnmTS0GSgksY343rgoS5jYXsGARzlxO3xEMXeY7lgAHRprlTH5cIgY+MAQHzExF/JsUm1PoKir/IuWY3N32E51mUiOvRfLiU2LefArniYaxxkMhTWA28MnzX3Gy+/0lysar/FiNR/gAvpClKN8mhWSKTlgMLFB6HdNtg6NdRAIqQCaSRJ5wIKoOoWlTO36eZhhkev5b8JmSNXHU5Dw19jXKNOEpRaGhJm2SedLFV8Xcs92JPHLYZrxPGlzd9BaC3cXQFDUAj/fZrH00ceXnR2k16/JV86P/WkKlmbaNnxvOR1zCdwWMdsmQcvTrx4bqMZLXv6JHKlszj9yjlyCfOtBPV4QN4svpOBAmaOiAS38azCM/cBmDR9WlQVn0Lu+sTL5cvTRf8oz4wdb21wHFPaNqTHCsIfoVpJC/rHcnARndJyeFafiDbRtrFonVqOGLYIUteY/5nkUtLZX9h/U2d0fKhbTi9UxUvIl52bjGGQfTufTaQqxEJJo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
