travis:
  secure:
    BINSTAR_TOKEN: HnCj9qKFCn3vBPusrzmq3+wHjyE1JNioF8BmDGJNTR2bMwCKY9BNem7s61mA+lsn1/sq71+Wg2y76OsiBkh7m15xgo5wHaIyL4ucJ9j6lmTzeKQSgDDWBiAbvOp2GmeikPqxyj3FjF1AtUiYqVHHcax+qvbj/5DARHlFxM4/7rAWwjNF+eV15AyVMni9AwsHD97k8doclXAiaImXH4we4Rxa3NbL6GzWQU8VH3Ze/cFCgiSRcLoIxf0/++lit/BnRL/m3rOurU5daf/vbfNAytfpjH/qUcoahFRN3EuZSjE/7PM18fpPbkPnVm+iPB7nSfsCbChvlNVkFuT2q+OdeozMD2i4HpOXIsCUcdg+ODteml6vRZrDGL4mKliFYXoBT/U5lfflwRujWRIv8xgQc/3hxPJdK8n89SYT5GIktCu69KvTfZPLCx4/ko4xo244imKYq8FQ9q3UhEi6Gk3cxCszIaR+pGDsBcxFS2nJR/45csC6dg0uUbNoqeX+qXqIZtXlvprbozw5xXmA2h5/aKvqUGUx6/uIGjOOuggxSo4+7hIWVGP4EC6s4uatd6OegaXwutWGhfHIUjt/H1imiGPSS8Cas9/I3mtY9VEHLPoZ5EnkJXdcp+kRp0/X2fWYZ4x8xSN2SSXgwZsTqlJjrUjF/TSj5eTMXXOmYqf6NVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
