travis:
  secure:
    BINSTAR_TOKEN: RKcksJnqEp1MXKg39/19CepOJb0FBxqYKFUdEFeEfLQqmm3IOJziQIxDffRNFMP5v9um5vJDlgeVzodXJKMlQS+fXZlw2wC2/VYwto7x0MB8dYoNrhI2SqldF0cOqL2gij/j4dBgA+mZXqSPWd/NSCg1WC9J+tNCi0dNFu3+NWrnyR3ijGuekDGCx1zKgdYaKS7Mq+qvD++i7uWAwt+4Ye2+trFqzi3nhcxyvrPkf6gtfJyGSfB6baoCiEFImmF0cCzo4RG14bT7mnzzw1Xv6Gwr2bvXoIVakWCnq6KB7ATgKFelMZId3Lt5Z0Pmnr8o+1Qk69vvM4f2/mHagZMA/zNFleZgX0ibgog5F8zA444PTrEz2gzzEVDkOVByJkhs4TRdCP5aU9RX04dO+zLOYyx9YxxsI+XHcAdc3GqOcRU6b1qgb+akNHLy4nAAEqy+dtbDq0FzAzEm7zAZ4frLz8FpKjWmcCc8874YekR43jUxKlSdu0Yl43prad/EfzPLlvm/Tk0vkRE+HQYX9MVUAXXbgEwnXDj17VT0A3E7cNpFFT8FzhWEZC01YwUNnOBpGhKkBNS/MMNfDqSrr1pdJoX6y173EjABm8LHIBBzNPCFv+5oyJ3na/d7YrCIcICBOSaNobZH4bFEWYx85DC3Si4GHXEfPPoSYzfpCS7VIck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
